version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: wick-cassandra
    ports:
      - "9042:9042"  # CQL native transport port
      - "7002:7000"  # Inter-node communication (changed from 7000)
      - "7003:7001"  # SSL inter-node communication (changed from 7001)
      - "7200:7199"  # JMX (changed from 7199)
    volumes:
      - cassandra-data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=WickCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra", "-e describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  cassandra-data: 